website/blueprints/auth.py
from flask import Blueprint, render_template, request, make_response
from flask import redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from website.models import User
from website import db
from website import __init__
from website.forms import RegisterForm, LoginForm
from website.utils.additional_functions import no_cache
import uuid


auth = Blueprint('auth', __name__)


@auth.route('/signup', methods=['POST', 'GET'])
def signup():
    reg_data = RegisterForm(request.form)
    if not reg_data.validate_on_submit():
        print(reg_data.errors.items())
        return render_template("signup.html", form=reg_data)
    first_name, last_name, email = reg_data.first_name.data, reg_data.last_name.data, reg_data.email.data
    address, postcode, cart = reg_data.address.data, reg_data.postcode.data, reg_data.cart.data
    password = reg_data.password.data
    if not User.query.filter_by(email=email).first():
        user = User(public_id=str((uuid.uuid4())),
                    is_admin=False,
                    email=email,
                    password=generate_password_hash(password),
                    first_name=first_name,
                    last_name=last_name,
                    address=address,
                    postcode=int(postcode),
                    cart=cart)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for("main.index"), 301)
    else:
        return render_template("signup.html", form=reg_data, errors=["User already exists"])


@auth.route('/login', methods=['POST', 'GET'])
def login():
    auth_data = LoginForm(request.form)
    if not auth_data.validate_on_submit():
        return render_template("login.html", form=auth_data, errors=[])
    email = auth_data.email.data
    password = auth_data.password.data
    remember = auth_data.remember.data
    user = User.query.filter_by(email=email).first()
    if user:
        user_password_hash = user.password
        if check_password_hash(user_password_hash, password):
            login_user(user, remember=remember)
            return redirect(url_for("main.index"), 301)
    return render_template("login.html", form=auth_data, errors=["Login or password are incorrect"])


@auth.route("/logout")
@no_cache
def logout():
    logout_user()
    resp = redirect(url_for("main.index"), 301)
    return resp

website/blueprints/main.py
from flask import Blueprint, render_template
from flask_login import current_user

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/profile')
def profile():
    return "Profile!"

website/blueprints/shop.py
from flask import Blueprint, render_template
from website.models import *

shop = Blueprint('shop', __name__)


@shop.route('/men', methods=['GET', 'POST'])
def men():
    items = Item.query.filter(Item.sex == 1).all()
    params = {
        "title": "Мужская одежда",
        "brand_list": Brand.query.all(),
        "material_list": Material.query.all(),
        "color_list": Color.query.all(),
        "type_list": Type.query.all(),
        "logined": True
    }
    if request.method == "POST":
        print(request.form)
    return render_template('shop.html', **params)


@shop.route('/women')
def women():
    items = Item.query.filter(Item.sex == 2).all()
    params = {
        "title": "Женская одежда",
        "logined": True
    }
    if request.method == "POST":
        print(request.form)
    return render_template('shop.html', **params)


@shop.route('/kids')
def kids():
    items = Item.query.filter(Item.sex == 3).all()
    params = {
        "title": "Детская одежда",
        "logined": True
    }
    if request.method == "POST":
        print(request.form)
    return render_template('shop.html', **params)

website/templates/admin_panel.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{url_for('static', filename='css/style.css')}"/>
    <title>{{ title }}</title>
</head>
<body style="margin: 5% 20%;">
<div class="error-messages">
    {% if errors %}
    {% for error in errors %}
    <div class="message-header">
        <p>Error</p>
    </div>
    <div class="message-body">
        {{ error }}
    </div>
    {% endfor %}
    {% endif %}
</div>
<div>
    <form class="login_form" enctype="multipart/form-data" method="post" action="/admin">
        {{ form.hidden_tag() }}
        <h1>Добавить вещь</h1>
        <div class="form-group">
            <input class="form-control" placeholder="Введите артикул" name="article" type="text">
            <div class="form-errors">
                {% for error in form.vendor_code.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input class="form-control" placeholder="Введите название" name="name" type="text">
            <div class="form-errors">
                {% for error in form.name.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input class="form-control" placeholder="Введите описание" name="description" type="text">
            <div class="form-errors">
                {% for error in form.description.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input class="form-control" placeholder="Введите цену" name="price" type="number">
            <div class="form-errors">
                {% for error in form.price.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input class="form-control" placeholder="Введите количество на складе" name="amount" type="number">
            <div class="form-errors">
                {% for error in form.amount.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <select class="form-select" name="brand" required>
                <option disabled selected>Выберите бренд</option>
                {% for brand in brand_list %}
                    <option>{{ brand }}</option>
                {% endfor %}
            </select>
            <div class="form-errors">
                {% for error in form.brand.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <select class="form-select" name="material" required>
                <option disabled selected>Выберите материал</option>
                {% for material in material_list %}
                    <option>{{ material }}</option>
                {% endfor %}
            </select>
            <div class="form-errors">
                {% for error in form.material.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <select class="form-select" name="color" required>
                <option disabled selected>Выберите цвет</option>
                {% for color in color_list %}
                    <option>{{ color }}</option>
                {% endfor %}
            </select>
            <div class="form-errors">
                {% for error in form.color.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <select class="form-select" name="type" required>
                <option disabled selected>Выберите тип одежды</option>
                {% for type in type_list %}
                    <option>{{ type }}</option>
                {% endfor %}
            </select>
            <div class="form-errors">
                {% for error in form.cloth_type.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <select class="form-select" name="sex" required>
                <option disabled selected>Выберите пол</option>
                {% for sex in sex_list %}
                    <option>{{ sex }}</option>
                {% endfor %}
            </select>
            <div class="form-errors">
                {% for error in form.sex.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <input type="file" name="images" multiple accept="image/png,image/jpeg"><br>
            <div class="form-errors">
                {% for error in form.pictures.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
</div>
</body>
</html>

website/templates/index.html
{% extends "layout.html" %}

{% block head %} {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}"/>
{% endblock %}

{% block content %}
    <div class="width-wrapper">
        <div class="mainpage-banners">
            <h3 class="choose">Выберите интересующий вас раздел</h3>
            <div>
                <a style="background-image: url(../static/img/women_banner.webp); height: 510px" href="/women">
                    <div class="banner-text">Женщинам</div>
                </a>
                <a style="background-image: url(../static/img/men_banner.webp); height: 510px" href="/men">
                    <div class="banner-text">Мужчинам</div>
                </a>
                <a style="background-image: url(../static/img/kids_banner.webp); height: 510px" href="/kids">
                    <div class="banner-text" style="">Детям</div>
                </a>
            </div>
        </div>
        <img src="static/img/brands.png" alt="brands" style="width:100%; position:relative; margin-bottom:40px">
    </div>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <title>Магазин одежды</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
                href="https://fonts.googleapis.com/css2?family=Arvo&display=swap"
                rel="stylesheet"
        />
        <link
                rel="stylesheet"
                href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
                integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
                crossorigin="anonymous"
        />
        <script
                src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"
        ></script>
        <script
                src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"
        >

        </script>
        <script
                src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"
        ></script>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="display: flex; justify-content: space-between;">
    <a class="navbar-brand" href="{{ url_for('main.index') }}" style="">Lorem Ipsum</a>
    <div class="header-choose">
        <a href="/women">Женщинам</a>
        <a href="/men">Мужчинам</a>
        <a href="/kids">Детям</a>
    </div>
    <div>
        {% if current_user.is_authenticated %}
            <a
                    href="{{ url_for('main.profile') }}"
                    class="btn btn-outline-primary"
                    role="button"
                    style="margin-left: 4px;"
            >Профиль</a>
            <a
                    href="{{ url_for('auth.logout') }}"
                    class="btn btn-outline-danger"
                    role="button"
                    style="margin-left: 4px;"
            >Выйти</a>
            </div>
        {% else %}
            <a
                    href="{{ url_for('auth.signup') }}"
                    class="btn btn-outline-primary"
                    role="button"
            >Регистрация</a>
            <a
                    href="{{ url_for('auth.login') }}"
                    class="btn btn-outline-primary"
                    role="button"
                    style="margin-left: 4px;"
            >Войти</a>
        {% endif %}
</nav>
{% block content %} {% endblock %}
<footer>
    <div class="width-wrapper">
        <div class="footer-inner">
            <details class="footer-item" open="open">
                <summary class="footer-title">Помощь</summary>
                <div class="footer-details">
                    <a class="footer-link" href="">Статус заказа по номеру</a>
                    <a class="footer-link" href="">Центр поддержки</a>
                    <a class="footer-link" href="">Как оформить заказ</a>
                    <a class="footer-link" href="">Как выбрать размер</a>
                    <a class="footer-link" href="">Условия доставки</a>
                    <a class="footer-link" href="">Мои заказы</a>
                    <a class="footer-link" href="">Возврат</a>
                    <a class="footer-link" href="">Публичная оферта</a>
                    <a class="footer-link" href="">Программа лояльности</a>
                    <a class="footer-link" href="">Часто задаваемые вопросы</a>
                </div>
            </details>
            <details class="footer-item" open="open">
                <summary class="footer-title">О нас</summary>
                <div class="footer-details">
                    <a class="footer-link" href="">Вакансии</a>
                    <a class="footer-link" href="">ВКонтакте</a>
                    <a class="footer-link" href="">YouTube</a>
                    <a class="footer-link" href="">Instagram</a>
                    <a class="footer-link" href="">Telegram</a>
                    <a class="footer-link" href="">TikTok</a>
                </div>
            </details>
            <details class="footer-item" open="open">
                <summary class="footer-title">Доставка с примеркой</summary>
                <div class="footer-details">
                    <p class="footer-link">У нас есть собственная служба доставки Lamoda Express,
                        которая работает в 66 крупнейших городах России: Москва и МО, Санкт-Петербург, Нижний Новгород,
                        Новосибирск, Екатеринбург, Самара, Тольятти, Тюмень, Челябинск и другие. Срок доставки — 1-2
                        дня.
                        Бесплатная доставка по всей России! Примерьте перед покупкой! Интернет-магазин Lamoda даёт
                        возможность примерить одежду, обувь и другие товары перед оплатой заказа курьеру.
                        Оплачивайте только то, что вам подошло и понравилось!</p>
                </div>
            </details>
            <details class="footer-item" open="open">
                <summary class="footer-title">Оплата и возврат</summary>
                <div class="footer-details">
                    <p class="footer-link">Интернет-магазин одежды и обуви Lamoda.ru
                        позволяет вернуть товар в течение 14 дней с момента покупки. Вернуть товары можно
                        как с курьером до оплаты заказа, так и по почте или в одном из пунктов выдачи заказов в Москве.
                        Вы можете оплатить покупки не только наличными, но и банковскими картами. У всех курьеров Lamoda
                        Express при себе есть терминал для оплаты картами.
                        Теперь купить обувь и одежду можно в 2 клика, не выходя из дома!</p>
                </div>
            </details>
        </div>
    </div>
</footer>
</body>
</html>

website/templates/login.html
{% extends "layout.html" %} {% block title %} Log In {% endblock %} {% block head %} {{ super() }}
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/style.css') }}"
    />
{% endblock %} {% block content %}
    <div class="width-wrapper">
        <div class="error-messages">
            {% if errors %}
                {% for error in errors %}
                    <div class="message-header">
                        <p>Error</p>
                    </div>
                    <div class="message-body">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="login-form" style="margin: 3rem auto">
            <form method="POST" action="/login">
                {{ form.hidden_tag() }}
                <h2>Войти в учётную запись</h2>
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            aria-describedby="emailHelp"
                            placeholder="Enter email"
                    />
                    <div class="form-errors">
                        {% for error in form.email.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input
                            type="password"
                            class="form-control"
                            id="password"
                            name="password"
                            placeholder="Password"
                    />
                    <div class="form-errors">
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-check" style="margin: 1rem auto">
                    <input type="checkbox" class="form-check-input" id="remember"/>
                    <label class="form-check-label" for="remember">Запомнить</label>
                </div>
                <button class="btn btn-primary" type="submit">Войти</button>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/signup.html
{% extends "layout.html" %} {% block title %} Sign Up {% endblock %} {% block head %} {{ super() }}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='styles/style.css') }}"
    />
{% endblock %} {% block content %}
    <div class="width-wrapper" style="margin: 3rem auto;">
        <div class="error-messages">
            {% if errors %}
                {% for error in errors %}
                    <div class="message-header">
                        <p>Error</p>
                    </div>
                    <div class="message-body">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="signup-form">
            <form method="POST" action="/signup">
                {{ form.hidden_tag() }}
                <h2>Регистрация</h2>
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            aria-describedby="emailHelp"
                            placeholder="Введите e-mail"
                    />
                    <div class="form-errors">
                        {% for error in form.email.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input
                            type="password"
                            class="form-control"
                            id="password"
                            name="password"
                            placeholder="Пароль"
                    />
                    <div class="form-errors">
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="repeated_password">Повторите пароль</label>
                    <input
                            type="password"
                            class="form-control"
                            id="repeated_password"
                            name="repeated_password"
                            placeholder="Повторите пароль"
                    />
                    <div class="form-errors">
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="first_name">Имя</label>
                    <input
                            type="text"
                            class="form-control"
                            id="first_name"
                            name="first_name"
                            placeholder="Имя"
                    />
                    <div class="form-errors">
                        {% for error in form.first_name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="last_name">Фамилия</label>
                    <input
                            type="text"
                            class="form-control"
                            id="last_name"
                            name="last_name"
                            placeholder="Фамилия"
                    />
                    <div class="form-errors">
                        {% for error in form.last_name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="address">Адрес</label>
                    <input
                            type="text"
                            class="form-control"
                            id="address"
                            name="address"
                            placeholder="Адрес"
                    />
                    <div class="form-errors">
                        {% for error in form.address.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="postcode">Индекс</label>
                    <input
                            type="text"
                            class="form-control"
                            id="postcode"
                            name="postcode"
                            placeholder="Индекс"
                    />
                    <div class="form-errors">
                        {% for error in form.postcode.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}